name: venv
channels:
  - intel
  - conda-forge
  - defaults
dependencies:
  - python>=3.10.0
  - cython>=0.29.28
  - pygments>=2.11.2
  - numpy=1.22.3
  - scipy>=1.7.3
  - mkl-devel>=2021.4.0
  - scikit-learn>=1.0.2
  - matplotlib>=3.5.1
