[tool.pyright]
exclude = ["venv", ".venv", ".direnv"]
root = "KoLesky"
venvPath = "."
venv = "venv"

[tool.ruff]
line-length = 79
ignore = ["E731"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
